In [1]:
#Triangle bilocal network. Alice, Bob and Charlie share Bell states
#Each one of them makes parity measurements.
#Let's just try to test if the entropies were right first.
using QBase

In [2]:
#|0>
k0 = [1,0]
#k1
k1 = [0,1]
#|000>
k000 = [1,0,0,0,0,0,0,0]
#|011>
k011 = [0,0,0,1,0,0,0,0]
#|101>
k101 = [0,0,0,0,0,1,0,0]
#|k110>
k110 = [0,0,0,0,0,0,1,0];
#|010>
k010 = [0,0,1,0,0,0,0,0]
#|111>
k111 = [0,0,0,0,0,0,0,1];

In [3]:
rho_clas_ABC = (1/4)*(k000*k000' + k011*k011' + k101*k101' + k110*k110');

In [4]:
rho_ABC = QBase.States.DensityMatrix(rho_clas_ABC)

8×8 QBase.States.DensityMatrix:
 0.25+0.0im  0.0+0.0im  0.0+0.0im  …   0.0+0.0im   0.0+0.0im  0.0+0.0im
  0.0+0.0im  0.0+0.0im  0.0+0.0im      0.0+0.0im   0.0+0.0im  0.0+0.0im
  0.0+0.0im  0.0+0.0im  0.0+0.0im      0.0+0.0im   0.0+0.0im  0.0+0.0im
  0.0+0.0im  0.0+0.0im  0.0+0.0im      0.0+0.0im   0.0+0.0im  0.0+0.0im
  0.0+0.0im  0.0+0.0im  0.0+0.0im      0.0+0.0im   0.0+0.0im  0.0+0.0im
  0.0+0.0im  0.0+0.0im  0.0+0.0im  …  0.25+0.0im   0.0+0.0im  0.0+0.0im
  0.0+0.0im  0.0+0.0im  0.0+0.0im      0.0+0.0im  0.25+0.0im  0.0+0.0im
  0.0+0.0im  0.0+0.0im  0.0+0.0im      0.0+0.0im   0.0+0.0im  0.0+0.0im

In [5]:
S_ABC = QBase.Information.von_neumann_entropy(rho_ABC)

2.0

In [6]:
QBase.States.is_density_matrix(rho_clas_ABC)

true

In [7]:
using QBase: QMath
rho_BC = QMath.partial_trace(rho_clas_ABC,[2,2,2],1)#tracing out A

4×4 Array{Float64,2}:
 0.25  0.0   0.0   0.0
 0.0   0.25  0.0   0.0
 0.0   0.0   0.25  0.0
 0.0   0.0   0.0   0.25

In [8]:
rho_C0 = QMath.partial_trace(rho_BC,[2,2],1)#tracing out B
rho_C = QBase.States.DensityMatrix(rho_C0)

2×2 QBase.States.DensityMatrix:
 0.5+0.0im  0.0+0.0im
 0.0+0.0im  0.5+0.0im

In [9]:
S_C = QBase.Information.von_neumann_entropy(rho_C)

1.0

In [10]:
#Parity measurements
#|00>
k00 = [1,0,0,0]
#|11>
k11 = [0,0,0,1]
#|01>
k01 = [0,1,0,0]
#|10>
k10 = [0,0,1,0]
#|001>
k001 = kron(k00,k1)

8-element Array{Int64,1}:
 0
 1
 0
 0
 0
 0
 0
 0

In [11]:
#Even Parity:
P0 = k00*k00' + k11*k11'
#Odd Parity
P1 = k10*k10' + k01*k01'

4×4 Array{Int64,2}:
 0  0  0  0
 0  1  0  0
 0  0  1  0
 0  0  0  0

In [12]:
#Density matrix
k000000 = kron(k000,k000)
k000101 = kron(k000,k101)
k010010 = kron(k010,k010)
k010111 = kron(k010,k111)
k101000 = kron(k101,k000)
k101101 = kron(k101,k101)
k111010 = kron(k111,k010)
k111111 = kron(k111,k111)

64-element Array{Int64,1}:
 0
 0
 0
 0
 0
 0
 0
 0
 0
 0
 0
 0
 0
 ⋮
 0
 0
 0
 0
 0
 0
 0
 0
 0
 0
 0
 1

In [13]:
g_state = (k000000 + k000101 + k010010 + k010111 + k101000 + k101101 + k111010 + k111111)

64-element Array{Int64,1}:
 1
 0
 0
 0
 0
 1
 0
 0
 0
 0
 0
 0
 0
 ⋮
 0
 0
 0
 0
 0
 0
 1
 0
 0
 0
 0
 1

In [14]:
g_den_matrix0 = (1/8)*g_state*g_state'

64×64 Array{Float64,2}:
 0.125  0.0  0.0  0.0  0.0  0.125  0.0  …  0.125  0.0  0.0  0.0  0.0  0.125
 0.0    0.0  0.0  0.0  0.0  0.0    0.0     0.0    0.0  0.0  0.0  0.0  0.0
 0.0    0.0  0.0  0.0  0.0  0.0    0.0     0.0    0.0  0.0  0.0  0.0  0.0
 0.0    0.0  0.0  0.0  0.0  0.0    0.0     0.0    0.0  0.0  0.0  0.0  0.0
 0.0    0.0  0.0  0.0  0.0  0.0    0.0     0.0    0.0  0.0  0.0  0.0  0.0
 0.125  0.0  0.0  0.0  0.0  0.125  0.0  …  0.125  0.0  0.0  0.0  0.0  0.125
 0.0    0.0  0.0  0.0  0.0  0.0    0.0     0.0    0.0  0.0  0.0  0.0  0.0
 0.0    0.0  0.0  0.0  0.0  0.0    0.0     0.0    0.0  0.0  0.0  0.0  0.0
 0.0    0.0  0.0  0.0  0.0  0.0    0.0     0.0    0.0  0.0  0.0  0.0  0.0
 0.0    0.0  0.0  0.0  0.0  0.0    0.0     0.0    0.0  0.0  0.0  0.0  0.0
 0.0    0.0  0.0  0.0  0.0  0.0    0.0  …  0.0    0.0  0.0  0.0  0.0  0.0
 0.0    0.0  0.0  0.0  0.0  0.0    0.0     0.0    0.0  0.0  0.0  0.0  0.0
 0.0    0.0  0.0  0.0  0.0  0.0    0.0     0.0    0.0  0.0  0.0  0.0  0.0
 ⋮        

In [15]:
#eigvals(g_den_matrix0) #if this is a pure state, should have given only 1 and 0 for eigvals

UndefVarError: UndefVarError: eigvals not defined

In [16]:
QBase.States.is_density_matrix(g_den_matrix0)

true

In [17]:
g_den_matrix = QBase.States.DensityMatrix(g_den_matrix0)

64×64 QBase.States.DensityMatrix:
 0.125+0.0im  0.0+0.0im  0.0+0.0im  …  0.0+0.0im  0.0+0.0im  0.125+0.0im
   0.0+0.0im  0.0+0.0im  0.0+0.0im     0.0+0.0im  0.0+0.0im    0.0+0.0im
   0.0+0.0im  0.0+0.0im  0.0+0.0im     0.0+0.0im  0.0+0.0im    0.0+0.0im
   0.0+0.0im  0.0+0.0im  0.0+0.0im     0.0+0.0im  0.0+0.0im    0.0+0.0im
   0.0+0.0im  0.0+0.0im  0.0+0.0im     0.0+0.0im  0.0+0.0im    0.0+0.0im
 0.125+0.0im  0.0+0.0im  0.0+0.0im  …  0.0+0.0im  0.0+0.0im  0.125+0.0im
   0.0+0.0im  0.0+0.0im  0.0+0.0im     0.0+0.0im  0.0+0.0im    0.0+0.0im
   0.0+0.0im  0.0+0.0im  0.0+0.0im     0.0+0.0im  0.0+0.0im    0.0+0.0im
   0.0+0.0im  0.0+0.0im  0.0+0.0im     0.0+0.0im  0.0+0.0im    0.0+0.0im
   0.0+0.0im  0.0+0.0im  0.0+0.0im     0.0+0.0im  0.0+0.0im    0.0+0.0im
   0.0+0.0im  0.0+0.0im  0.0+0.0im  …  0.0+0.0im  0.0+0.0im    0.0+0.0im
   0.0+0.0im  0.0+0.0im  0.0+0.0im     0.0+0.0im  0.0+0.0im    0.0+0.0im
   0.0+0.0im  0.0+0.0im  0.0+0.0im     0.0+0.0im  0.0+0.0im    0.0+0.0im
      ⋮          

In [18]:
SqABC = QBase.Information.von_neumann_entropy(g_den_matrix)

-0.0

In [19]:
#Checking if it is a pure state:
using LinearAlgebra
tr(g_den_matrix*g_den_matrix)

1.0 + 0.0im

In [20]:
#Finding p(0,0,0)
P000 = kron(kron(P0,P0),P0)#hhas expected dimensions

64×64 Array{Int64,2}:
 1  0  0  0  0  0  0  0  0  0  0  0  0  …  0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  1  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0  …  0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0  …  0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  1    

In [21]:
p000 = tr(P000*g_den_matrix) #matches expectations!

0.25 + 0.0im

In [22]:
P111 = kron(kron(P1,P1),P1)
p111 = tr(P111*g_den_matrix) #also matches expectations!

0.0 + 0.0im

In [23]:
#Ok, so it works. What now? We see if we get the same results with the classical density matrix.
#Getting only diagonal terms:
class_den_matrix0 = ones(64,64)
n = 0
for i = 1:64
    for j = 1:64
        if(i==j)
            class_den_matrix0[i,j] = g_den_matrix[i,j];
            if(g_den_matrix[i,j] != 0)
                n = n+1; #n is the number of nonzero diagonal terms. we have 8.
            end            
        else
            class_den_matrix0[i,j] = 0;
        end
    end
end

In [24]:
class_den_matrix = QBase.States.DensityMatrix(class_den_matrix0)

64×64 QBase.States.DensityMatrix:
 0.125+0.0im  0.0+0.0im  0.0+0.0im  …  0.0+0.0im  0.0+0.0im    0.0+0.0im
   0.0+0.0im  0.0+0.0im  0.0+0.0im     0.0+0.0im  0.0+0.0im    0.0+0.0im
   0.0+0.0im  0.0+0.0im  0.0+0.0im     0.0+0.0im  0.0+0.0im    0.0+0.0im
   0.0+0.0im  0.0+0.0im  0.0+0.0im     0.0+0.0im  0.0+0.0im    0.0+0.0im
   0.0+0.0im  0.0+0.0im  0.0+0.0im     0.0+0.0im  0.0+0.0im    0.0+0.0im
   0.0+0.0im  0.0+0.0im  0.0+0.0im  …  0.0+0.0im  0.0+0.0im    0.0+0.0im
   0.0+0.0im  0.0+0.0im  0.0+0.0im     0.0+0.0im  0.0+0.0im    0.0+0.0im
   0.0+0.0im  0.0+0.0im  0.0+0.0im     0.0+0.0im  0.0+0.0im    0.0+0.0im
   0.0+0.0im  0.0+0.0im  0.0+0.0im     0.0+0.0im  0.0+0.0im    0.0+0.0im
   0.0+0.0im  0.0+0.0im  0.0+0.0im     0.0+0.0im  0.0+0.0im    0.0+0.0im
   0.0+0.0im  0.0+0.0im  0.0+0.0im  …  0.0+0.0im  0.0+0.0im    0.0+0.0im
   0.0+0.0im  0.0+0.0im  0.0+0.0im     0.0+0.0im  0.0+0.0im    0.0+0.0im
   0.0+0.0im  0.0+0.0im  0.0+0.0im     0.0+0.0im  0.0+0.0im    0.0+0.0im
      ⋮          

In [25]:
p000_class = tr(P000*class_den_matrix)

0.25 + 0.0im

In [26]:
p111_class = tr(P111*class_den_matrix)

0.0 + 0.0im

In [27]:
P110 = kron(kron(P1,P1),P0)
P101 = kron(kron(P1,P0),P1)
P011 = kron(kron(P0,P1),P1)
P001 = kron(kron(P0,P0),P1);

In [28]:
p110_class = tr(P110*class_den_matrix)

0.25 + 0.0im

In [29]:
p011_class = tr(P011*class_den_matrix)

0.25 + 0.0im

In [30]:
p101_class = tr(P101*class_den_matrix)

0.25 + 0.0im

In [31]:
p001_class = tr(P001*class_den_matrix)

0.0 + 0.0im

# Bell Measurements

In [32]:
dens_beta0 = (1/2)*(k00*k00' + k00*k11' + k11*k00' + k11*k11')
dens_beta1 = (1/2)*((k01 + k10)*(k01 + k10)')
dens_beta2 = (1/2)*((k00 - k11)*(k00 - k11)')
dens_beta3 = (1/2)*((k01 - k10)*(k01 - k10)')

4×4 Array{Float64,2}:
 0.0   0.0   0.0  0.0
 0.0   0.5  -0.5  0.0
 0.0  -0.5   0.5  0.0
 0.0   0.0   0.0  0.0

In [33]:
Bell000 = kron(kron(dens_beta0,dens_beta0),dens_beta0)
Bell001 = kron(kron(dens_beta0,dens_beta0),dens_beta1)

64×64 Array{Float64,2}:
 0.0  0.0    0.0    0.0  0.0  0.0  0.0  …  0.0  0.0  0.0  0.0    0.0    0.0
 0.0  0.125  0.125  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.125  0.125  0.0
 0.0  0.125  0.125  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.125  0.125  0.0
 0.0  0.0    0.0    0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0    0.0    0.0
 0.0  0.0    0.0    0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0    0.0    0.0
 0.0  0.0    0.0    0.0  0.0  0.0  0.0  …  0.0  0.0  0.0  0.0    0.0    0.0
 0.0  0.0    0.0    0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0    0.0    0.0
 0.0  0.0    0.0    0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0    0.0    0.0
 0.0  0.0    0.0    0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0    0.0    0.0
 0.0  0.0    0.0    0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0    0.0    0.0
 0.0  0.0    0.0    0.0  0.0  0.0  0.0  …  0.0  0.0  0.0  0.0    0.0    0.0
 0.0  0.0    0.0    0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0    0.0    0.0
 0.0  0.0    0.0    0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0   

In [34]:
p_Bell000 = tr(Bell000*g_den_matrix) #1/16

0.0625 + 0.0im

In [35]:
p_Bell001 = tr(Bell001*g_den_matrix)

0.0 + 0.0im

In [36]:
outcomes = [dens_beta0,dens_beta1,dens_beta2,dens_beta3]

4-element Array{Array{Float64,2},1}:
 [0.5 0.0 0.0 0.5; 0.0 0.0 0.0 0.0; 0.0 0.0 0.0 0.0; 0.5 0.0 0.0 0.5]
 [0.0 0.0 0.0 0.0; 0.0 0.5 0.5 0.0; 0.0 0.5 0.5 0.0; 0.0 0.0 0.0 0.0]
 [0.5 0.0 0.0 -0.5; 0.0 0.0 0.0 0.0; 0.0 0.0 0.0 0.0; -0.5 0.0 0.0 0.5]
 [0.0 0.0 0.0 0.0; 0.0 0.5 -0.5 0.0; 0.0 -0.5 0.5 0.0; 0.0 0.0 0.0 0.0]

In [37]:
#Measurement matrix
function measurement(a,b,c)
    kron(kron(a,b),c)
end

measurement (generic function with 1 method)

In [38]:
#Testing if it works as I think it should.
testmeasurement = measurement(outcomes[1],outcomes[1],outcomes[1])
testp000B = tr(testmeasurement*g_den_matrix)
#It does.

0.0625 + 0.0im

In [39]:
#Calculates probabilities, given outcomes a,b,c and a density matrix
function prob(a,b,c,dens_matrix)
    tr(measurement(a,b,c)*dens_matrix)
end
prob(outcomes[1],outcomes[1],outcomes[1],g_den_matrix)#works just fine

0.0625 + 0.0im

In [40]:
#Calculating all probs!!!
bell_probs = ones(4,4,4)
for i = 1:4
    for j = 1:4
        for k = 1:4
            bell_probs[i,j,k] = prob(outcomes[i],outcomes[j],outcomes[k],g_den_matrix);
            print("p(",i,",",j,",",k,") = ",bell_probs[i,j,k],"\n")
        end
    end
end

           

p(1,1,1) = 0.0625
p(1,1,2) = 0.0
p(1,1,3) = 0.0
p(1,1,4) = 0.0
p(1,2,1) = 0.0
p(1,2,2) = 0.0625
p(1,2,3) = 0.0
p(1,2,4) = 0.0
p(1,3,1) = 0.0
p(1,3,2) = 0.0
p(1,3,3) = 0.0625
p(1,3,4) = 0.0
p(1,4,1) = 0.0
p(1,4,2) = 0.0
p(1,4,3) = 0.0
p(1,4,4) = 0.0625
p(2,1,1) = 0.0
p(2,1,2) = 0.0625
p(2,1,3) = 0.0
p(2,1,4) = 0.0
p(2,2,1) = 0.0625
p(2,2,2) = 0.0
p(2,2,3) = 0.0
p(2,2,4) = 0.0
p(2,3,1) = 0.0
p(2,3,2) = 0.0
p(2,3,3) = 0.0
p(2,3,4) = 0.0625
p(2,4,1) = 0.0
p(2,4,2) = 0.0
p(2,4,3) = 0.0625
p(2,4,4) = 0.0
p(3,1,1) = 0.0
p(3,1,2) = 0.0
p(3,1,3) = 0.0625
p(3,1,4) = 0.0
p(3,2,1) = 0.0
p(3,2,2) = 0.0
p(3,2,3) = 0.0
p(3,2,4) = 0.0625
p(3,3,1) = 0.0625
p(3,3,2) = 0.0
p(3,3,3) = 0.0
p(3,3,4) = 0.0
p(3,4,1) = 0.0
p(3,4,2) = 0.0625
p(3,4,3) = 0.0
p(3,4,4) = 0.0
p(4,1,1) = 0.0
p(4,1,2) = 0.0
p(4,1,3) = 0.0
p(4,1,4) = 0.0625
p(4,2,1) = 0.0
p(4,2,2) = 0.0
p(4,2,3) = 0.0625
p(4,2,4) = 0.0
p(4,3,1) = 0.0
p(4,3,2) = 0.0625
p(4,3,3) = 0.0
p(4,3,4) = 0.0
p(4,4,1) = 0.0625
p(4,4,2) = 0.0
p(4,4,3) = 0.0
p(4,4,4

In [41]:
#Calculating all probabilities for classical state
bell_probs_class = ones(4,4,4)
for i = 1:4
    for j = 1:4
        for k = 1:4
            bell_probs_class[i,j,k] = prob(outcomes[i],outcomes[j],outcomes[k],class_den_matrix);
            print("p(",i,",",j,",",k,") = ",bell_probs_class[i,j,k],"\n")
        end
    end
end


p(1,1,1) = 0.03125
p(1,1,2) = 0.0
p(1,1,3) = 0.03125
p(1,1,4) = 0.0
p(1,2,1) = 0.0
p(1,2,2) = 0.03125
p(1,2,3) = 0.0
p(1,2,4) = 0.03125
p(1,3,1) = 0.03125
p(1,3,2) = 0.0
p(1,3,3) = 0.03125
p(1,3,4) = 0.0
p(1,4,1) = 0.0
p(1,4,2) = 0.03125
p(1,4,3) = 0.0
p(1,4,4) = 0.03125
p(2,1,1) = 0.0
p(2,1,2) = 0.03125
p(2,1,3) = 0.0
p(2,1,4) = 0.03125
p(2,2,1) = 0.03125
p(2,2,2) = 0.0
p(2,2,3) = 0.03125
p(2,2,4) = 0.0
p(2,3,1) = 0.0
p(2,3,2) = 0.03125
p(2,3,3) = 0.0
p(2,3,4) = 0.03125
p(2,4,1) = 0.03125
p(2,4,2) = 0.0
p(2,4,3) = 0.03125
p(2,4,4) = 0.0
p(3,1,1) = 0.03125
p(3,1,2) = 0.0
p(3,1,3) = 0.03125
p(3,1,4) = 0.0
p(3,2,1) = 0.0
p(3,2,2) = 0.03125
p(3,2,3) = 0.0
p(3,2,4) = 0.03125
p(3,3,1) = 0.03125
p(3,3,2) = 0.0
p(3,3,3) = 0.03125
p(3,3,4) = 0.0
p(3,4,1) = 0.0
p(3,4,2) = 0.03125
p(3,4,3) = 0.0
p(3,4,4) = 0.03125
p(4,1,1) = 0.0
p(4,1,2) = 0.03125
p(4,1,3) = 0.0
p(4,1,4) = 0.03125
p(4,2,1) = 0.03125
p(4,2,2) = 0.0
p(4,2,3) = 0.03125
p(4,2,4) = 0.0
p(4,3,1) = 0.0
p(4,3,2) = 0.03125
p(4,3,3) = 0.0